
[general]
	#Whether to show icons next to the bars
	display_icons = true
	full_absorption_bar = false
	full_armor_bar = false
	full_toughness_bar = false
	display_low_armor_warning = true
	show_saturation_bar = true
	show_hydration_bar = true
	show_held_food_overlay = true
	show_held_drink_overlay = true
	show_exhaustion_overlay = true
	show_thirst_exhaustion_overlay = true
	#Range: 0.0 ~ 1.7976931348623157E308
	transition_speed = 3.0
	hunger_bar_color = "#B34D00"
	hunger_bar_debuff_color = "#249016"
	thirstr_bar_color = "#1C5EE4"
	thirst_bar_debuff_color = "#5A891C"
	air_bar_color = "#00E6E6"
	saturation_bar_color = "#FFCC00"
	saturation_bar_debuff_color = "#87BC00"
	hydration_bar_color = "#00A3E2"
	hydration_bar_debuff_color = "#85CF25"
	lava_bar_color = "#FF8000"
	flight_bar_color = "#FFFFFF"
	armor_color_values = ["#AAAAAA", "#FF5500", "#FFC747", "#27FFE3", "#00FF00", "#7F00FF"]
	armor_toughness_color_values = ["#AAAAAA", "#FF5500", "#FFC747", "#27FFE3", "#00FF00", "#7F00FF"]
	absorption_color_values = ["#D4AF37", "#C2C73B", "#8DC337", "#36BA77", "#4A5BC4", "#D89AE2", "#DF9DC7", "#DFA99D", "#D4DF9D", "#3E84C6", "#B8C1E8", "#DFDFDF"]
	absorption_poison_color_values = ["#D4AF37", "#C2C73B", "#8DC337", "#36BA77", "#4A5BC4", "#D89AE2", "#DF9DC7", "#DFA99D", "#D4DF9D", "#3E84C6", "#B8C1E8", "#DFDFDF"]
	absorption_wither_color_values = ["#D4AF37", "#C2C73B", "#8DC337", "#36BA77", "#4A5BC4", "#D89AE2", "#DF9DC7", "#DFA99D", "#D4DF9D", "#3E84C6", "#B8C1E8", "#DFDFDF"]
	normal_colors = ["#FF0000", "#FFFF00", "#00FF00"]
	normal_fractions = [0.25, 0.5, 0.75]
	poisoned_colors = ["#00FF00", "#55FF55", "#00FF00"]
	poisoned_fractions = [0.25, 0.5, 0.75]
	withered_colors = ["#555555", "#AAAAAA", "#555555"]
	withered_fractions = [0.25, 0.5, 0.75]
	left_order = ["health", "armor", "absorption", "lavacharm", "lavacharm2"]
	right_order = ["blood", "health_mount", "food", "thirst_level", "parcool:stamina", "feathers", "armor_toughness", "air", "flighttiara", "decay"]

