
["Mystical Agradditions"]
	#Set how many augments can be placed on the insanium armor
	#Range: 1 ~ 2
	insanium_armor_augments = 2
	#Set how many augments can be placed on the insanium tools
	#Range: 1 ~ 2
	insanium_tools_augments = 2

["Vampirism Compat"]
	#Enable the Thirstless Augment
	thirstless_augment = true
	#Enable the Daywalker Augment
	daywalker_augment = true

["Mob Drops"]
	#Wither drops insanium essence when killed with an Insanium weapon.
	wither_insanium = true
	#Ender Dragon drops insanium essence when killed with an Insanium weapon.
	dragon_insanium = true

