
#General configuration options.
[General]
	#The amount of Dragon Scales that an Ender Dragon will drop when killed.
	#Range: 0 ~ 64
	dragonScalesAmount = 8
	#The duration of each Essence Apples effects in seconds.
	#Range: > 1
	essenceAppleDuration = 180
	#Can tier 6 crops be fertilized using Mystical Fertilizer or Fertilized Essence?
	fertilizableTier6Crops = false
	#Should Cruxes for disabled crops be hidden and not have recipes?
	hideUnusedCruxes = false
	#The percentage chance that a Wither will drop a Withering Soul when killed.
	#Range: 0.0 ~ 1.0
	witheringSoulChance = 0.35

#World generation options.
[World]
	#How many Nether Inferium Ore veins should spawn in a chunk.
	#Range: > 0
	netherInferiumSpawnRate = 16
	#The maximum amount of Nether Inferium Ore blocks that can spawn in a vein.
	#Range: > 0
	netherInferiumSpawnSize = 8
	#How many End Inferium Ore veins should spawn in a chunk.
	#Range: > 0
	endInferiumSpawnRate = 16
	#Should End Prosperity Ore generate in the world?
	generateEndProsperityOre = true
	#The maximum amount of End Inferium Ore blocks that can spawn in a vein.
	#Range: > 0
	endInferiumSpawnSize = 8
	#The minimum Y level that Prosperity Ore veins can spawn.
	#Range: 0 ~ 128
	endProsperitySpawnMinY = 10
	#Should Nether Prosperity Ore generate in the world?
	generateNetherProsperityOre = true
	#The maximum Y level that Prosperity Ore veins can spawn.
	#Range: 0 ~ 128
	endProsperitySpawnMaxY = 100
	#The maximum Y level that End Inferium Ore veins can spawn.
	#Range: 0 ~ 128
	endInferiumSpawnMaxY = 100
	#The minimum Y level that Nether Prosperity Ore veins can spawn.
	#Range: 0 ~ 128
	netherProsperitySpawnMinY = 10
	#Should Nether Inferium Ore generate in the world?
	generateNetherInferiumOre = true
	#The maximum Y level that Nether Inferium Ore veins can spawn.
	#Range: 0 ~ 128
	netherInferiumSpawnMaxY = 100
	#How many End Prosperity Ore veins should spawn in a chunk.
	#Range: > 0
	endProsperitySpawnRate = 12
	#The maximum amount of End Prosperity Ore blocks that can spawn in a vein.
	#Range: > 0
	endProsperitySpawnSize = 8
	#The maximum amount of Nether Prosperity Ore blocks that can spawn in a vein.
	#Range: > 0
	netherProsperitySpawnSize = 8
	#How many Nether Prosperity Ore veins should spawn in a chunk.
	#Range: > 0
	netherProsperitySpawnRate = 12
	#The maximum Y level that Nether Prosperity Ore veins can spawn.
	#Range: 0 ~ 128
	netherProsperitySpawnMaxY = 100
	#The minimum Y level that Nether Inferium Ore veins can spawn.
	#Range: 0 ~ 128
	netherInferiumSpawnMinY = 10
	#The minimum Y level that End Inferium Ore veins can spawn.
	#Range: 0 ~ 128
	endInferiumSpawnMinY = 10
	#Should End Inferium Ore generate in the world?
	generateEndInferiumOre = true

